### ISSUE TITLE
1.2.0 breaks styles

### ISSUE THREAD

**Issue by beautyfree** [yldio/styled-is#43]
This code:
![image](https://user-images.githubusercontent.com/656531/54193961-2ff34500-44cc-11e9-9166-bb3f42d80bec.png)

Produces this styles with v1.2.0:
![image](https://user-images.githubusercontent.com/656531/54193770-cd9a4480-44cb-11e9-804e-b1089eb3ce78.png)

**Comment by SaraVieira** [comment]
Hey!

Can you please create a CodeSandbox so I can test and fix ?

**Comment by mboudriga** [comment]
I'll take a look at this, I think I know whats happening

**Comment by SaraVieira** [comment]
Oh! Thanks man !!

**Comment by mboudriga** [comment]
I'm unable to test that it works for your specific scenario, but this works for something similar I setup locally: https://github.com/yldio/styled-is/pull/44

**Comment by SaraVieira** [comment]
I published as    1.2.1, @beautyfree Can you try please?

**Comment by mboudriga** [comment]
@beautyfree did you get a chance to test this?

**Comment by mboudriga** [comment]
@SaraVieira Do we want to just close this since its been two weeks?

**Comment by SaraVieira** [comment]
Yap! Im gonna close it!

Thanks again for your help!
