### ISSUE TITLE
styled-is breaks on function templates that return non-string values on newest version

### ISSUE THREAD

**Issue by CharlieMartell** [yldio/styled-is#45]
Seems the addition of 

```
const handleFunctions = (args, props) => {
  let css = '';
  for (let i = 1; i < args.length; i++) {
    if (typeof args[i] === 'function') {
      const output = args[i](props);
      if (output.includes(':')) {
        css += output;
      }
    }
  }

  if (css) {
    const newArgs = args.slice(0);
    const argCss = args[0].slice(1);
    argCss.unshift(css + newArgs[0][0]);
    newArgs[0] = argCss;
    return newArgs;
  }

  return args;
};
```

in https://github.com/yldio/styled-is/blob/master/src/index.js has caused styled-components like 
```
  ${is('something')`
    min-height: ${p => (p.expanded ? '50vh' : 0)};
  `};
```

to error out on `output.includes(':')` even though it is valid css here this worked back when instead of `handleFunctions` it used `css(...args);`

**Comment by mboudriga** [comment]
@CharlieMartell What do you mean by error out, can you post a screenshot?

**Comment by mboudriga** [comment]
Opened a pull request fixing this: https://github.com/yldio/styled-is/pull/46

**Comment by SaraVieira** [comment]
Closed by @mboudrig 😁
